[project]
name = "lotto"
version = "0.0.1"
description = "Default template for PDM package"
authors = [
    {name = "", email = ""},
]
dependencies = []
requires-python = ">=3.9.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
